### PR TITLE
CA-1 - Fix build

### LINKED ISSUE #1: Fix compilation
This repo was created by merging https://github.com/ultravioletrs/manager and and https://github.com/ultravioletrs/agent into monorepo.

Fix compilation errors by observing how Manager and Agent work individually and following the best practices used in the Magistrala project.

### PR DESCRIPTION
**Pull request by SammyOina**
Resolves #1 
Signed-off-by: SammyOina <sammyoina@gmail.com>

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM
